url: "https://loganmorto.github.io/Bancru-Concrete/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/Bancru-Concrete" # the subpath of your site, e.g. /blog
title: "Bancru Concrete" # the name of your site, e.g. ACME Corp.
